"""Conformance runner: `python -m etki_api.conformance <dist> [--report out.json]`.

Resolves the distribution's ``etki.adapters`` entry point → ``PluginSpec`` →
``spec.conformance()`` offline providers, binds them to the port contract
classes, runs pytest against a generated module, and converts the junitxml
into a machine-readable JSON report (plus a human summary on stdout).

Runs in the PLUGIN's CI with only ``etki-api[conformance]`` installed — etki
itself is never needed (`etki plugin verify` is a thin delegate to this)."""

from __future__ import annotations

import argparse
import json
import tempfile
import xml.etree.ElementTree as ET
from importlib import metadata
from pathlib import Path

from etki_api import PluginSpec
from etki_api import __version__ as _api_version

GROUP = "etki.adapters"

# The generated test module reads the bound provider instances from here at
# collection time (same process — pytest.main below).
_INSTANCES: dict[str, object] = {}

_GENERATED = '''\
"""Generated by etki_api.conformance.runner — binds spec.conformance() providers."""
import pytest

from etki_api.conformance import CONTRACTS
from etki_api.conformance import runner as _runner


def _bind(base, instance):
    class Bound(base):
        @pytest.fixture
        def provider(self):
            return instance

    return Bound


for _port, _instance in _runner._INSTANCES.items():
    _cls = _bind(CONTRACTS[_port], _instance)
    _cls.__name__ = f"Test{_port.title().replace('_', '')}Conformance"
    globals()[_cls.__name__] = _cls
'''


def _load_spec(dist_name: str) -> PluginSpec:
    dist = metadata.distribution(dist_name)  # raises PackageNotFoundError when absent
    eps = [ep for ep in dist.entry_points if ep.group == GROUP]
    if not eps:
        raise LookupError(f"{dist_name!r} dağıtımında {GROUP!r} entry point'i yok")
    spec = eps[0].load()
    if not isinstance(spec, PluginSpec):
        raise TypeError(f"{dist_name!r} entry point'i PluginSpec değil: {type(spec).__name__}")
    return spec


def _junit_to_results(xml_path: Path) -> list[dict]:
    results: list[dict] = []
    root = ET.parse(xml_path).getroot()
    for case in root.iter("testcase"):
        outcome, message = "passed", None
        for child in case:
            if child.tag in ("failure", "error"):
                outcome = "failed"
                message = (child.get("message") or "")[:500]
            elif child.tag == "skipped":
                outcome = "skipped"
                message = (child.get("message") or "")[:500]
        results.append(
            {
                "test": f"{case.get('classname', '')}.{case.get('name', '')}",
                "outcome": outcome,
                "message": message,
            }
        )
    return results


def run(dist_name: str, report_path: str | None = None) -> int:
    import pytest  # conformance extra — imported here so --help works without it

    try:
        spec = _load_spec(dist_name)
    except Exception as exc:  # noqa: BLE001 — CLI boundary: report, don't traceback
        print(f"conformance: {exc}")
        return 2
    if spec.conformance is None:
        print(
            f"conformance: {spec.name} PluginSpec'inde `conformance` factory yok — "
            "offline sağlayıcı üreten bir factory ekleyin (bkz. plugin kılavuzu)."
        )
        return 2

    _INSTANCES.clear()
    _INSTANCES.update(dict(spec.conformance().items()))
    unknown = set(_INSTANCES) - {
        "work_items", "code_repo", "documents", "llm", "embedding", "rerank",
        "registry_metadata", "request_intake", "response_channel",
    }
    if unknown:
        print(f"conformance: bilinmeyen port(lar): {sorted(unknown)}")
        return 2

    with tempfile.TemporaryDirectory(prefix="etki-conformance-") as tmp:
        test_file = Path(tmp) / "test_generated_conformance.py"
        test_file.write_text(_GENERATED, encoding="utf-8")
        junit = Path(tmp) / "junit.xml"
        exit_code = pytest.main(
            [
                str(test_file),
                "-q",
                f"--junit-xml={junit}",
                "-o", "asyncio_mode=auto",
                "-o", "addopts=",  # neutralize any inherited repo addopts
                "-p", "no:cacheprovider",
            ]
        )
        results = _junit_to_results(junit) if junit.exists() else []

    passed = sum(1 for r in results if r["outcome"] == "passed")
    failed = sum(1 for r in results if r["outcome"] == "failed")
    skipped = sum(1 for r in results if r["outcome"] == "skipped")
    conformant = failed == 0 and passed > 0 and int(exit_code) in (0,)
    report = {
        # Version-compat matrix fields — the marketplace index consumes these.
        "plugin": spec.name,
        "version": metadata.version(dist_name),
        "etki_api_version": _api_version,
        "api_compat": spec.api_compat,
        "ports": sorted(_INSTANCES),
        "passed": passed,
        "failed": failed,
        "skipped": skipped,
        "conformant": conformant,
        "results": results,
    }
    if report_path:
        Path(report_path).write_text(
            json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    verdict = "UYUMLU ✓" if conformant else "UYUMSUZ ✗"
    print(
        f"conformance: {spec.name} {report['version']} (etki-api {_api_version}, "
        f"aralık {spec.api_compat}) → {verdict}  "
        f"[{passed} geçti / {failed} kaldı / {skipped} atlandı]"
    )
    return 0 if conformant else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m etki_api.conformance",
        description="Bir plugin dağıtımını port sözleşmelerine karşı doğrular.",
    )
    parser.add_argument("dist", help="dağıtım adı, örn. etki-plugin-linear")
    parser.add_argument("--report", default=None, help="JSON rapor çıktı yolu")
    args = parser.parse_args(argv)
    return run(args.dist, args.report)
